import { schemaMigrations, addColumns, createTable } from '@nozbe/watermelondb/Schema/migrations';

/** Add a migration step here every time SCHEMA_VERSION is bumped. */
export const migrations = schemaMigrations({
  migrations: [
    {
      toVersion: 2,
      steps: [
        addColumns({
          table: 'products',
          columns: [
            { name: 'image_url', type: 'string', isOptional: true },
            { name: 'on_hand_qty', type: 'number', isOptional: true },
            { name: 'min_qty', type: 'number' },
          ],
        }),
        addColumns({ table: 'collections', columns: [{ name: 'shared_at', type: 'number', isOptional: true }] }),
        addColumns({ table: 'attachments', columns: [{ name: 'parent_type', type: 'string' }] }),
        createTable({
          name: 'follow_ups',
          columns: [
            { name: 'customer_id', type: 'string', isIndexed: true },
            { name: 'visit_id', type: 'string', isOptional: true },
            { name: 'type', type: 'string' },
            { name: 'reason', type: 'string', isOptional: true },
            { name: 'promised_amount', type: 'number', isOptional: true },
            { name: 'promised_date', type: 'string', isOptional: true },
            { name: 'due_at', type: 'number', isIndexed: true },
            { name: 'notes', type: 'string', isOptional: true },
            { name: 'status', type: 'string', isIndexed: true },
            { name: 'completed_at', type: 'number', isOptional: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'day_sessions',
          columns: [
            { name: 'date', type: 'string', isIndexed: true },
            { name: 'started_at', type: 'number' },
            { name: 'ended_at', type: 'number', isOptional: true },
            { name: 'start_lat', type: 'number', isOptional: true },
            { name: 'start_lng', type: 'number', isOptional: true },
            { name: 'end_lat', type: 'number', isOptional: true },
            { name: 'end_lng', type: 'number', isOptional: true },
            { name: 'start_note', type: 'string', isOptional: true },
            { name: 'end_note', type: 'string', isOptional: true },
            { name: 'cash_in_hand_end', type: 'number', isOptional: true },
            { name: 'status', type: 'string' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'handovers',
          columns: [
            { name: 'receipt_no', type: 'string', isOptional: true },
            { name: 'date', type: 'string', isIndexed: true },
            { name: 'amount', type: 'number' },
            { name: 'mode', type: 'string' },
            { name: 'reference_no', type: 'string', isOptional: true },
            { name: 'bank_name', type: 'string', isOptional: true },
            { name: 'notes', type: 'string', isOptional: true },
            { name: 'attachments', type: 'string' },
            { name: 'status', type: 'string' },
            { name: 'sync_error', type: 'string', isOptional: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'expenses',
          columns: [
            { name: 'expense_number', type: 'string', isOptional: true },
            { name: 'date', type: 'string', isIndexed: true },
            { name: 'category', type: 'string' },
            { name: 'description', type: 'string' },
            { name: 'amount', type: 'number' },
            { name: 'payment_method', type: 'string' },
            { name: 'notes', type: 'string', isOptional: true },
            { name: 'attachments', type: 'string' },
            { name: 'status', type: 'string' },
            { name: 'review_note', type: 'string', isOptional: true },
            { name: 'sync_error', type: 'string', isOptional: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'leads',
          columns: [
            { name: 'firm_name', type: 'string' },
            { name: 'contact_name', type: 'string', isOptional: true },
            { name: 'mobile', type: 'string', isOptional: true },
            { name: 'email', type: 'string', isOptional: true },
            { name: 'gstin', type: 'string', isOptional: true },
            { name: 'address_line', type: 'string', isOptional: true },
            { name: 'city', type: 'string', isOptional: true },
            { name: 'state', type: 'string', isOptional: true },
            { name: 'pincode', type: 'string', isOptional: true },
            { name: 'latitude', type: 'number', isOptional: true },
            { name: 'longitude', type: 'number', isOptional: true },
            { name: 'notes', type: 'string', isOptional: true },
            { name: 'attachments', type: 'string' },
            { name: 'status', type: 'string' },
            { name: 'customer_id', type: 'string', isOptional: true },
            { name: 'customer_code', type: 'string', isOptional: true },
            { name: 'sync_error', type: 'string', isOptional: true },
            { name: 'created_at', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'targets',
          columns: [
            { name: 'period', type: 'string', isIndexed: true },
            { name: 'collection_target', type: 'number' },
            { name: 'sales_target', type: 'number' },
            { name: 'visits_target', type: 'number' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'order_history',
          columns: [
            { name: 'order_no', type: 'string' },
            { name: 'customer_id', type: 'string', isIndexed: true },
            { name: 'order_date', type: 'string' },
            { name: 'status', type: 'string' },
            { name: 'net_amount', type: 'number' },
            { name: 'items', type: 'string' },
            { name: 'updated_at', type: 'number' },
          ],
        }),
      ],
    },
  ],
});
